name: genomehubs-index-directory
description: |
  Index a directory using updated files or fallback to previous version
inputs:
  directory:
    description: Directory containing files to index
    required: true
    type: string
  dockerversion:
    description: Docker container version
    required: true
    type: string
  flags:
    description: Additional flags to pass to genomehubs index
    default: ""
    type: string
  release:
    description: GoaT release version
    required: true
    type: string
  resources:
    description: Path to local resources
    required: true
    type: string
  type:
    description: Directory type
    required: true
    type: choice
    choices:
      - assembly
      - feature
      - sample
      - taxon

runs:
  using: composite
  steps:
    # - id: snapshot index(es)
    #   description: Make a snapshot of the current index in case of need to rollback
    - id: list-files
      run: |
        echo directory=${{ inputs.directory }}
        echo type=${{ inputs.type }}
        echo flags=${{ inputs.flags }}
        ls ${{ inputs.resources }}/${{ inputs.directory }}
        ls sources/${{ inputs.directory }}
      shell: bash
    - id: attempt-1
      run: |
        echo trying with files from resources
      shell: bash
    - id: attempt-2
      run: |
        echo retrying with files from sources
      shell: bash
