name: genomehubs-index-directory
description: |
  Index a directory using updated files or fallback to previous version
inputs:
  directory:
    description: Directory containing files to index
    required: true
    type: string
  dockerversion:
    description: Docker container version
    required: true
    type: string
  flags:
    description: Additional flags to pass to genomehubs index
    default: ""
    type: string
  release:
    description: GoaT release version
    required: true
    type: string
  resources:
    description: Path to local resources
    required: true
    type: string
  type:
    description: Directory type
    required: true
    type: choice
    choices:
      - assembly
      - feature
      - sample
      - taxon

runs:
  using: composite
  steps:
    # - id: snapshot index(es)
    #   description: Make a snapshot of the current index in case of need to rollback
    - id: set-DIRNAME-variable
      run: |
        echo DIRNAME=${{ inputs.directory }} >> GITHUB_ENV
      shell: bash
    - id: list-files
      run: |
        echo directory=${{ inputs.directory }}
        echo type=${{ inputs.type }}
        echo flags=${{ inputs.flags }}
        echo DIRNAME=$DIRNAME
        echo DIRNAME=$([ -d sources/$DIRNAME ] && $DIRNAME || ${DIRNAME//-/_}) >> GITHUB_ENV
      shell: bash
    - id: attempt-1
      continue-on-error: true
      run: |
        echo trying with files from resources
        ls ${{ inputs.resources }}/${{ inputs.directory }}
      shell: bash
    - id: attempt-2
      if: steps.attempt-1.outcome == 'failure'
      run: |
        echo retrying with files from sources
        ls sources/$DIRNAME
      shell: bash
