name: Contact Us
description: Get in touch with the GoaT team.
title: '[Contact Us]: '
labels: ['connect']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for getting in touch with us.
  - type: dropdown
    id: team
    attributes:
      label: For which aspect of GoaT do you need assistance?
      options:
        - data submission
        - data retrieval
        - code
        - GoaT web page
        - EBP
        - other
    validations:
      required: true
  - type: textarea
    id: message
    attributes:
      label: Message
      description: Please use the field below to reach out. If you have a problem, data or feature request, please create an issue on the respective GitHub page () directly.
    validations:
      required: true
