name: GoaT Data Change
description: This request type should be used when new or more appropriate sources are found to describe species metadata than what is currently displayed.
title: Data Change [TITLE]
labels: [data-change-request]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a new primary value for metadata on GoaT. Thanks for taking the time to contribute. 
  - type: checkboxes
    id: category
    attributes:
      label: What is your request type?
      description: Use this field to inform if you would like to add missing data values, correct existing values on GoaT or set an existing value as the sumarry value for a taxon.
      options:
        - label: new_data_value
        - label: data_correction
        - label: set_existing_value_as_primary
  - type: textarea
    id: attribute
    attributes:
      label: Attribute label
      description: Please add the label in lowercase for the attribute you are submitting the request, unless it is a proper name.
      placeholder: e.g., chromosome_number
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of request
      description: Please provide a description of the issue.
    validations:
      required: true
  - type: textarea
    id: values
    attributes:
      label: New values
      description: Please add the new values for the selected attribute by taxon. Please use lower-case and separate multiple values by a comma.
      placeholder: 
        bos taurus | XX,XY
        cat | XX
    validations:
      required: true
  - type: textarea
    id: taxonomy
    attributes:
      label: Taxon- or tissue- restricted
      description: Is the value restricted? Please indicate if there are any taxonomic or biological constraints for the attribute and values. Include the ncbi taxonomy ID when referring to a specific taxon group.
      placeholder: e.g., male plant-specific, term applies only to taxID 35493 males, Streptophyta. not applicable to Basidiomycota Fungi, taxID 5204. Germline restricted.
    validations:
      required: false
  - type: textarea
    id: DOI
    attributes:
      label: Reference
      description: Include the DOI / PubMed ID to refer to any relevant article that provides additional information about the suggested value and taxa.
      placeholder: e.g., https://doi.org/10.1038/nrg2008
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
