name: GoaT Tutorial Request
description: Unsure about a query or feature? Request a tutorial for GoaT Wiki/ Youtube Channel.
title: New Tutorial: [TITLE]
labels: "project:goat :goat:"
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a tutorial on GoaT. Thanks for taking the time to contribute. 
  - type: checkboxes
    id: confirmation
    attributes:
      label: tutorial type
      description: Use this field to inform if you would like to request a new tutorial  or refine an existing tutorial on [GoaT-Wiki](https://github.com/genomehubs/goat-data/wiki) or [YouTube channel](https://www.youtube.com/@genomesonatree)
      options:
        - label: new_tutorial
        - label: clarification_of_existing_tutorial
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of request
      description: Please provide a description of the issue.
    validations:
      required: true
  - type: input
    id:  format
    attributes:
      label: Tutorial Format
      description: Please indicate your preferred method for the tutorial 
      placeholder:  decision-tree
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
