name: GoaT Tutorial Request
description: Want help with a query or feature? Request a tutorial on the GoaT wiki or Youtube channel.
title: New Tutorial [TITLE]
labels: "project:goat :goat:, process:documentation, stack:ui, stack:data"
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a GoaT tutorial. Thanks for taking the time to contribute. 
  - type: checkboxes
    id: confirmation
    attributes:
      label: tutorial type
      description: Use this field if you would like to request a new, or an update to an existing, tutorial on the [GoaT-Wiki](https://github.com/genomehubs/goat-data/wiki) or [YouTube channel](https://www.youtube.com/@genomesonatree)
      options:
        - label: new_tutorial
        - label: clarification_of_existing_tutorial
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of request
      description: Please describe what you would like the tutorial to cover.
    validations:
      required: true
  - type: input
    id:  format
    attributes:
      label: Tutorial Format
      description: Please indicate your preferred format for the tutorial 
      placeholder:  "text description, video, decision tree, etc."
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any related context, specific examples or screenshots here.
