file:
  format: csv
  header: true
  name: kewplantcvalues_tblCoreFields.csv.gz
  source: Kew Plant DNA C-values Database
  source_url: https://cvalues.science.kew.org
  display_group: genome_size
attributes:
  c_value:
    bins:
      min: -2.5
      max: 2.5
      count: 10
      scale: log10
    constraint:
      max: 200
      min: 0
    description: 1C value
    display_level: 1
    display_name: C value
    index: 18
    separator:
      - ","
      - "(?<!e)-"
    summary:
      - mean
      - median
      - max
      - min
    traverse: mean
    type: half_float
    units: pgDNA
  c_value_method:
    constraint:
      enum:
        - Unknown
        - Biochemical Analysis
        - Feulgen Image Analysis Densitometry
        - Flow Cytometry
        - Feulgen Densitometry
        - Feulgen Densitometry & Flow Cytometry
        - Microdensitometry
        - Pulse field gel electrophoresis
        - Reassociation kinetics
        - Whole genome sequencing
    description: C value estimation method
    display_level: 2
    display_name: C value method
    index: 27
    summary: list
    translate:
      -: Unknown
      Ch: Biochemical Analysis
      CIA: Feulgen Image Analysis Densitometry
      FC:?: Flow Cytometry
      FC:DAPI: Flow Cytometry
      FC:EB: Flow Cytometry
      FC:EB & O: Flow Cytometry
      FC:Hoechst: Flow Cytometry
      FC:MI: Flow Cytometry
      FC:PI: Flow Cytometry
      FC:PI & EB: Flow Cytometry
      FC:SYBR: Flow Cytometry
      Fe: Feulgen Densitometry
      Fe & FC:EB: Feulgen Densitometry & Flow Cytometry
      Fe & FC:PI: Feulgen Densitometry & Flow Cytometry
      M:DAPI: Microdensitometry
      M:H: Microdensitometry
      M:PI: Microdensitometry
      PFGE: Pulse field gel electrophoresis
      RK: Reassociation kinetics
      WGS: Whole genome sequencing
    traverse: false
    type: keyword
  chromosome_number:
    bins:
      min: 0
      max: 10
      count: 10
      scale: log2
    constraint:
      max: 2000
      min: 0
    description: Chromosome number
    display_level: 1
    display_group: karyotype
    display_name: Chromosome number
    index: 12
    separator:
      - ","
      - "-"
    summary:
      - median_high
      - mode
      - max
      - min
    traverse: median_high
    type: short
  genome_size:
    bins:
      min: 6
      max: 11
      count: 10
      scale: log10
    constraint:
      min: 0
    description: Genome size
    display_level: 1
    display_name: Genome size
    function: "{} * 978000000"
    index: 18
    separator:
      - ","
      - "(?<!e)-"
    summary:
      - mean
      - median
      - max
      - min
    traverse: mean
    type: long
    units: bases
taxonomy:
  genus:
    index: 5
  species:
    index: [5, 7]
    join: " "
  family:
    index: 2
  subspecies:
    index: [5, 7, 8]
    join: " "
