name: update-ncbi-datasets
on:
  workflow_call:
    inputs:
      taxroot:
        required: true
        type: string

jobs:
  fetch-ncbi-datasets-zip:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch NCBI TAXROOT datasets zip
        run: |
          echo CMD="datasets download genome taxon ${{ inputs.taxroot }} --no-progressbar --dehydrated --filename ${{ inputs.taxroot }}.zip" >> GITHUB_ENV
          echo FALLBACK="s3://goat/resources/${{ inputs.taxroot }}.zip" >> GITHUB_ENV
          echo LOCAL=./resources >> GITHUB_ENV
          ./scripts/fetch-or-fallback.sh
