name: update-ncbi-datasets
on:
  workflow_call:
    inputs:
      taxroot:
        required: true
        type: string
    resources:
      taxroot:
        required: true
        type: string

jobs:
  fetch-ncbi-datasets-zip:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch NCBI TAXROOT datasets zip
        run: |
          CMD="chmod 755 ${{ inputs.local }}/datasets && ${{ inputs.local }}/datasets download genome taxon ${{ inputs.taxroot }} --no-progressbar --dehydrated --filename ${{ inputs.taxroot }}.zip" \
          FALLBACK="s3://goat/resources/${{ inputs.taxroot }}.zip" \
          RESOURCES=${{ inputs.local }} \
          ./scripts/update-resources/fetch-or-fallback.sh
