name: fetch-resources-taxroot
on:
  workflow_call:
    inputs:
      resources:
        required: true
        type: string
      taxroot:
        required: true
        type: string

jobs:
  fetch-blobtoolkit:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch BlobToolKit
        run: |
          CMD="docker run --rm --network=host \
          -v `pwd`:/genomehubs/tmp \
          genomehubs/genomehubs:$DOCKERVERSION bash -c \
            \"genomehubs parse \
              --btk --btk-root ${{ inputs.taxroot }} --outfile tmp/btk.tsv.gz\"" \
          FALLBACK=s3://goat/resources/btk.tsv.gz \
          RESOURCES=${{ inputs.resources }} \
          ./scripts/update-resources/fetch-or-fallback.sh

  fetch-ncbi-datasets-zip:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch NCBI TAXROOT datasets zip
        run: |
          CMD="chmod 755 ${{ inputs.resources }}/datasets && ${{ inputs.resources }}/datasets download genome taxon ${{ inputs.taxroot }} --no-progressbar --dehydrated --filename ${{ inputs.taxroot }}.zip" \
          FALLBACK="s3://goat/resources/${{ inputs.taxroot }}.zip" \
          RESOURCES=${{ inputs.resources }} \
          ./scripts/update-resources/fetch-or-fallback.sh
