name: fetch-resources
on:
  workflow_call:
    inputs:
      dockerversion:
        required: true
        type: string
      resources:
        required: true
        type: string
      taxroot:
        required: true
        type: string

jobs:
  fetch-dockers:
    runs-on: [self-hosted, runner1]
    steps:
      - name: Get dockers
        run: |
          docker pull genomehubs/genomehubs:${{ inputs.dockerversion }}
          docker run --rm genomehubs/genomehubs sh -c 'echo $CONTAINER_VERSION'

  # fetch-ncbi-datasets:
  #   runs-on: [self-hosted, runner1]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Fetch NCBI datasets executable
  #       run: |
  #         CMD="curl -Ls https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets > datasets" \
  #         FALLBACK=s3://goat/resources/datasets \
  #         RESOURCES=${{ inputs.resources }} \
  #         ./scripts/update-resources/fetch-or-fallback.sh

  fetch-resources-taxroot:
    needs:
      - fetch-dockers
      # - fetch-ncbi-datasets
    strategy:
      matrix:
        taxroot: ${{ fromJson(inputs.taxroot) }}
    uses: ./.github/workflows/fetch-resources-taxroot.yml
    with:
      dockerversion: ${{ inputs.dockerversion }}
      resources: ${{ inputs.resources }}
      taxroot: ${{ matrix.taxroot }}

  # fetch-ncbi-taxdump:
  #   runs-on: [self-hosted, runner1]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Fetch NCBI taxdump
  #       run: |
  #         CMD="curl -s https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz \
  #         | tar xzf - nodes.dmp names.dmp" \
  #         FALLBACK=s3://goat/resources/new_taxdump/ncbi/nodes.dmp,s3://goat/resources/new_taxdump/ncbi/names.dmp \
  #         RESOURCES=${{ inputs.resources }}/new_taxdump/ncbi \
  #         ./scripts/update-resources/fetch-or-fallback.sh

  # fetch-refseq-organelles:
  #   runs-on: [self-hosted, runner1]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Fetch RefSeq organelles
  #       run: |
  #         CMD="docker run --rm --network=host \
  #         -v \$(pwd):/genomehubs/tmp \
  #         genomehubs/genomehubs:${{ inputs.dockerversion }} bash -c \
  #           \"genomehubs parse --refseq-organelles --outfile tmp/refseq_organelles.tsv.gz\"" \
  #         FALLBACK=s3://goat/resources/refseq_organelles.tsv.gz \
  #         RESOURCES=${{ inputs.resources }} \
  #         ./scripts/update-resources/fetch-or-fallback.sh

  # fetch-tolids:
  #   runs-on: [self-hosted, runner1]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Fetch ToLIDs
  #       run: |
  #         CMD="curl -s https://gitlab.com/wtsi-grit/darwin-tree-of-life-sample-naming/-/raw/master/tolids.txt \
  #         | gzip -c > tolids.tsv.gz" \
  #         FALLBACK=s3://goat/resources/tolids.tsv.gz \
  #         RESOURCES=${{ inputs.resources }} \
  #         ./scripts/update-resources/fetch-or-fallback.sh
