name: fetch-resources-ncbi-datasets-zip
on:
  workflow_call:
    inputs:
      resources:
        required: true
        type: string
      taxroot:
        required: true
        type: string

jobs:
  fetch-ncbi-datasets-zip:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch NCBI TAXROOT datasets zip
        run: |
          CMD="chmod 755 ${{ inputs.resources }}/datasets && ${{ inputs.resources }}/datasets download genome taxon ${{ inputs.taxroot }} --no-progressbar --dehydrated --filename ${{ inputs.taxroot }}.zip" \
          FALLBACK="s3://goat/resources/${{ inputs.taxroot }}.zip" \
          RESOURCES=${{ inputs.resources }} \
          ./scripts/update-resources/fetch-or-fallback.sh
