name: genomehubs-index
on:
  workflow_call:
    inputs:
      dockerversion:
        required: true
        type: string
      release:
        required: true
        type: string
      resources:
        required: true
        type: string

jobs:
  # fetch-dockers:
  #   runs-on: [self-hosted, runner1]
  #   steps:
  #     - name: Get dockers
  #       run: |
  #         docker pull genomehubs/genomehubs:${{ inputs.dockerversion }}
  #         docker run --rm genomehubs/genomehubs sh -c 'echo $CONTAINER_VERSION'

  index-directories:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3

      - name: Update version in config
        run: |
          yq '.common.hub.version="${{ inputs.release }}"' sources/goat.yaml > sources/goat.yaml.tmp && mv sources/goat.yaml.tmp sources/goat.yaml

      - name: Index assembly-data
        uses: ./.github/workflows/genomehubs-index-directory
        with:
          dockerversion: ${{ inputs.dockerversion }}
          release: ${{ inputs.release }}
          resources: ${{ inputs.resources }}
          directory: assembly-data
          type: assembly

      # - name: Index assembly-data-sample
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: assembly-data-sample
      #     type: sample

      # - name: Index ott3.3
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: ott3.3
      #     type: taxon

      # - name: Index tolids
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: tolids
      #     flags: --taxon-lookup any --taxon-spellcheck
      #     type: taxon

      # - name: Index genomesize-karyotype
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: genomesize-karyotype
      #     flags: --taxon-lookup any --taxon-spellcheck
      #     type: taxon

      # - name: Index regional-lists
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: regional-lists
      #     flags: --taxon-lookup any --taxon-spellcheck
      #     type: taxon

      # - name: Index uk-legislation
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: uk-legislation
      #     flags: --taxon-lookup any --taxon-spellcheck
      #     type: taxon

      # - name: Index btk
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: btk
      #     type: assembly

      # - name: Index lineages
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: lineages
      #     type: taxon

      # - name: Index status-lists
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: status-lists
      #     flags: --taxon-lookup any --taxon-spellcheck
      #     type: taxon

      # - name: Index assembly-data-taxon
      #   uses: ./.github/workflows/genomehubs-index-directory
      #   with:
      #     dockerversion: ${{ inputs.dockerversion }}
      #     release: ${{ inputs.release }}
      #     resources: ${{ inputs.resources }}
      #     directory: assembly-data-taxon
      #     type: taxon
