name: genomehubs-test
on:
  workflow_call:
    inputs:
      dockerversion:
        required: true
        type: string
      release:
        required: true
        type: string
      resources:
        required: true
        type: string

jobs:
  genomehubs-test:
    runs-on: [self-hosted, runner1]

    steps:
      - uses: actions/checkout@v4

      - name: Run genomehubs API tests
        run: |
          mkdir -p ${{ inputs.resources }}/projects
          docker run --rm \
            --network net-es \
            -e GH_RELEASE=${{ inputs.release }} \
            -e GH_HUBNAME=goat \
            -e GH_NODE=http://es1:9200 \
            -v `pwd`/sources/goat.yaml:/genomehubs/config/config.yaml \
            -v `pwd`/tests/api/generic:/genomehubs/tests \
            genomehubs/genomehubs-test:${{ inputs.dockerversion }} \
              genomehubs-test-api

      - name: Run genomehubs UI tests
        run: |
          mkdir -p ${{ inputs.resources }}/projects
          docker run --rm \
            --network net-es \
            -e GH_RELEASE=${{ inputs.release }} \
            -e GH_HUBNAME=goat \
            -e GH_API_PORT=3000 \
            -e GH_NODE=http://es1:9200 \
            -v `pwd`/tests/ui:/genomehubs/tests \
            -v ${{ inputs.resources }}/projects:/genomehubs/tests-out \
            genomehubs/genomehubs-test:${{ inputs.dockerversion }} \
              genomehubs-test-ui

      - name: Copy test images to S3
        run: |
          s3cmd put setacl --acl-public ${{ inputs.resources }}/projects s3://goat/releases/${{ inputs.release }}/ --recursive
