name: genomehubs-index
on:
  workflow_call:
    inputs:
      dockerversion:
        required: true
        type: string
      release:
        required: true
        type: string
      resources:
        required: true
        type: string

jobs:
  fetch-dockers:
    runs-on: [self-hosted, runner1]
    steps:
      - name: Get dockers
        run: |
          docker pull genomehubs/genomehubs:${{ inputs.dockerversion }}
          docker run --rm genomehubs/genomehubs sh -c 'echo $CONTAINER_VERSION'

  index-directories:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3

      - name: Check es health
        run: curl -s "es1:9200/_cat/health"

      - name: Index assembly-data
        uses: ./.github/workflows/genomehubs-index-directory
        with:
          dockerversion: ${{ inputs.dockerversion }}
          release: ${{ inputs.release }}
          resources: ${{ inputs.resources }}
          directory: assembly-data
          type: assembly

      - name: Index assembly-data-sample
        uses: ./.github/workflows/genomehubs-index-directory
        with:
          dockerversion: ${{ inputs.dockerversion }}
          release: ${{ inputs.release }}
          resources: ${{ inputs.resources }}
          directory: assembly-data-sample
          type: sample

      - name: Index ott3.3
        uses: ./.github/workflows/genomehubs-index-directory
        with:
          dockerversion: ${{ inputs.dockerversion }}
          release: ${{ inputs.release }}
          resources: ${{ inputs.resources }}
          directory: ott3.3
          type: taxon

      - name: Index ToLIDs
        uses: ./.github/workflows/genomehubs-index-directory
        with:
          dockerversion: ${{ inputs.dockerversion }}
          release: ${{ inputs.release }}
          resources: ${{ inputs.resources }}
          directory: tolids
          flags: --taxon-lookup any --taxon-spellcheck
          type: taxon

      - name: Index genomesize-karyotype
        uses: ./.github/workflows/genomehubs-index-directory
        with:
          dockerversion: ${{ inputs.dockerversion }}
          release: ${{ inputs.release }}
          resources: ${{ inputs.resources }}
          directory: genomesize-karyotype
          flags: --taxon-lookup any --taxon-spellcheck
          type: taxon
