name: get_ncbi_ena_tolids_daily
env:
  RELEASE: 2022.04.11

on: worflow_dispatch
  # schedule:
  #   # Runs "at 5 min past midnight" (see https://crontab.guru)
  #   - cron: '5 0 * * *'

jobs:
  check-health:
    runs-on:  self-hosted
    steps:
    - name: Check es health
      run:  curl -s "http://es1:9200/_cat/health"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get dockers
      run:  docker pull genomehubs/genomehubs:latest

  # get-ncbi-datasets:
  #   needs:    check-health
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Download NCBI datasets executable
  #       run: |
  #         curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > /tmp/datasets
  #         chmod a+x /tmp/datasets
  #     - name: Download NCBI eukaryota datasets zip
  #       run: |
  #         mkdir -p sources/assembly-data
  #         /tmp/datasets download genome taxon "Eukaryota" --dehydrated --filename sources/assembly-data/eukaryota.zip
  #         unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
  #     - name: Run docker genomehubs parse --ncbi-datasets
  #       run: |
  #         docker run --rm --network=host \
  #           -v `pwd`/sources:/genomehubs/sources \
  #           genomehubs/genomehubs:latest bash -c \
  #           "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
  #     - name: Clean up expanded zip
  #       run: |
  #           rm -rf sources/assembly-data/ncbi_dataset

  # get-refseq-organelles:
  #   needs:    check-health
  #   runs-on:  self-hosted
  #   steps:
  #     - name: Run docker genomehubs parse --refseq-organelles
  #       run: |
  #         docker run --rm --network=host \
  #           -v `pwd`/sources:/genomehubs/sources \
  #           genomehubs/genomehubs:latest bash -c \
  #           "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"

  get-ena-taxonomy-extra:
    needs:    check-health
    runs-on:  self-hosted
    steps:
    - name: Get extra ENA taxonomy nodes
      run:  |
        mkdir -p sources/ena-taxonomy
        cd sources/ena-taxonomy
        bash ../../scripts/get_ena_taxonomy_extra.bash
        rm -f ena-taxonomy.extra.jsonl ena-taxonomy.xml.taxids \
          resulttaxon.tax_tree2759.tsv ena-taxonomy.extra.prev.jsonl \
          ena-taxonomy.extra.prev.taxids resulttaxon.tax_tree2759.extra.curr.tsv \
          ena-taxonomy.extra.curr.jsonl
        git add ena-taxonomy.extra.json.gz
        git commit -m "update $RELEASE"
        git push
        cd   ../../

