name: get_ncbi_ena_tolids_daily
on:
  schedule:
    # Runs "at 0:13am" (see https://crontab.guru)
    - cron: '13 0 * * *'

jobs:
  get_ncbi_ena_tolids:
    runs-on: self-hosted
    steps:
      - name: Get dockers
        run:  docker pull genomehubs/genomehubs:latest
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Get release name from date
        run:  echo "RELEASE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Create a new branch
        run:  |
          git checkout -b $RELEASE
      - name: Download NCBI datasets executable
        run: |
          curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > datasets
          chmod a+x datasets
          sudo ip link set ens3 mtu 1500
      - name: Download NCBI eukaryota datasets zip
        run: |
          mkdir -p sources/assembly-data
          ./datasets download genome taxon "Eukaryota" --no-progressbar --dehydrated --filename sources/assembly-data/eukaryota.zip
          unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
      - name: Run docker genomehubs parse --ncbi-datasets
        run: |
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            genomehubs/genomehubs:latest bash -c \
            "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
      - name: Clean up expanded ncbi datasets zip
        run:  rm -rf sources/assembly-data/ncbi_dataset datasets
      - name: Run docker genomehubs parse --refseq-organelles
        run: |
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            genomehubs/genomehubs:latest bash -c \
            "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"
      - name: Get extra ENA taxonomy nodes
        run:  |
          mkdir -p sources/ena-taxonomy
          cd sources/ena-taxonomy
          bash ../../scripts/get_ena_taxonomy_extra.bash
          rm -f ena-taxonomy.extra.jsonl ena-taxonomy.xml.taxids \
            resulttaxon.tax_tree2759.tsv ena-taxonomy.extra.prev.jsonl \
            ena-taxonomy.extra.prev.taxids resulttaxon.tax_tree2759.extra.curr.tsv \
            ena-taxonomy.extra.curr.jsonl
          cd ../../
      - name: Get latest tolids
        run:  |
          mkdir -p sources/tolids
          curl -s https://gitlab.com/wtsi-grit/darwin-tree-of-life-sample-naming/-/raw/master/tolids.txt \
          | gzip -c > sources/tolids/tolids.tsv.gz
      - name: Commit files if needed
        run:  git commit -m "Add changes" -a || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.RELEASE }}
