name: init_index_fill

on: workflow_dispatch

jobs:
  check-health:
    runs-on:  self-hosted
    steps:
    - name: Check es health
      run:  curl -s "http://es1:9200/_cat/health"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get dockers
      run:  docker pull genomehubs/genomehubs:latest

  genomehubs-init:
    needs:
      - check-health
#       - get-ena-taxonomy-extra
    runs-on:  self-hosted
    steps:
      - name: Clean taxdump folder and delete indices
        run: |
          mkdir -p resources/taxdump
          rm -rf resources/taxdump/*
          curl -X DELETE "es1:9200/*"
      - name: Run genomehubs init
#         run: |
#           docker run --rm --network=host \
#             -v `pwd`/sources:/genomehubs/sources \
#             -v `pwd`/resources:/genomehubs/resources \
#             genomehubs/genomehubs:latest bash -c \
        run:  |
          source ~/genomehubsenv/bin/activate
          genomehubs init \
            --es-host http://es1:9200 \
            --taxonomy-source ncbi \
            --config-file sources/goat.yaml \
            --taxonomy-jsonl sources/ena-taxonomy/ena-taxonomy.extra.jsonl.gz \
            --taxonomy-ncbi-root 2759 \
            --taxon-preload


  index-assembly-data:
    needs:
      - check-health
      - genomehubs-init
#       - get-ncbi-datasets
#       - get-refseq-organelles
    runs-on:  self-hosted
    steps:
#       - name: Run docker genomehubs index --assembly-data
#         run: |
#           docker run --rm --network=host \
#             -v `pwd`/sources:/genomehubs/sources \
#             genomehubs/genomehubs:latest bash -c \
#             "genomehubs index \
#               --es-host http://es1:9200 \
#               --taxonomy-source ncbi \
#               --config-file sources/goat.yaml \
#               --assembly-dir sources/assembly-data"
      - name: Run genomehubs index --assembly-data
        run: |
          source ~/genomehubsenv/bin/activate
          genomehubs index \
            --es-host http://es1:9200 \
            --taxonomy-source ncbi \
            --config-file sources/goat.yaml \
            --assembly-dir sources/assembly-data

  fill:
    needs:
      - check-health
      - index-assembly-data
    runs-on:  self-hosted
    steps:
#       - name: Run docker genomehubs fill
#         run: |
#           docker run --rm --network=host \
#             -v `pwd`/sources:/genomehubs/sources \
#             genomehubs/genomehubs:latest bash -c \
#             "genomehubs fill \
#               --es-host http://es1:9200 \
#               --taxonomy-source ncbi \
#               --config-file sources/goat.yaml \
#               --traverse-root 2759 \
#               --traverse-infer-both"
      - name: Run genomehubs fill
        run: |
          source ~/genomehubsenv/bin/activate
          genomehubs fill \
            --es-host http://es1:9200 \
            --taxonomy-source ncbi \
            --config-file sources/goat.yaml \
            --traverse-root 2759 \
            --traverse-infer-both
