name: s3_release
on:
  workflow_dispatch:
  push:
  # schedule:
  #   - cron: "5 0 * * 1,2,3,4,5,6" # At 00:05 every MTWTFS
env:
  DOCKERVERSION: latest
  TAXROOT: '["9612"]'
  RESOURCES: /home/ubuntu/resources

jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      dockerversion: ${{ steps.dockerversion.outputs.dockerversion }}
      resources: ${{ steps.resources.outputs.resources }}
      taxroot: ${{ steps.taxroot.outputs.taxroot }}
    steps:
      - id: dockerversion
        run: |
          echo "dockerversion=$DOCKERVERSION" >> $GITHUB_OUTPUT
      - id: resources
        run: |
          echo "resources=$RESOURCES" >> $GITHUB_OUTPUT
      - id: taxroot
        run: |
          echo "taxroot=$TAXROOT" >> $GITHUB_OUTPUT

  fetch-resources:
    needs:
      - set-variables
    uses: ./.github/workflows/fetch-resources.yml
    with:
      dockerversion: ${{ needs.set-variables.outputs.dockerversion }}
      resources: ${{ needs.set-variables.outputs.resources }}
      taxroot: ${{ needs.set-variables.outputs.taxroot }}
