name: s3_release
on:
  workflow_dispatch:
  push:
  # schedule:
  #   - cron: "5 0 * * 1,2,3,4,5,6" # At 00:05 every MTWTFS
env:
  DOCKERVERSION: latest
  TAXROOT: '["9612"]'
  RESOURCES: /home/ubuntu/resources

jobs:
  get-dockers:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, runner1]
    steps:
      - name: Get dockers
        run: |
          exit 0
          # docker pull genomehubs/genomehubs:$DOCKERVERSION
          # docker run --rm genomehubs/genomehubs sh -c 'echo $CONTAINER_VERSION'

  set-taxroot:
    runs-on: ubuntu-latest
    outputs:
      taxroot: ${{ steps.taxroot-matrix.outputs.taxroot }}
      resources: ${{ steps.resources-directory.outputs.resources }}
    steps:
      - id: taxroot-matrix
        run: |
          echo "taxroot=$TAXROOT" >> $GITHUB_OUTPUT
      - id: resources-directory
        run: |
          echo "resources=$RESOURCES"
          echo "resources=$RESOURCES" >> $GITHUB_OUTPUT

  fetch-ncbi-taxdump:
    runs-on: [self-hosted, runner1]
    steps:
      - uses: actions/checkout@v3
      - name: Fetch NCBI taxdump
        run: |
          CMD=curl -s https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz \
          | tar xzf - nodes.dmp names.dmp && \
          CMD="curl -Ls https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets > datasets" \
          FALLBACK=s3://goat/resources/new_taxdump/ncbi/nodes.dmp,s3://goat/resources/new_taxdump/ncbi/names.dmp \
          RESOURCES=${{ needs.set-taxroot.outputs.resources }}/new_taxdump/ncbi \
          ./scripts/update-resources/fetch-or-fallback.sh

  fetch-ncbi-datasets:
    runs-on: [self-hosted, runner1]
    needs:
      - set-taxroot
    steps:
      - uses: actions/checkout@v3
      - name: Fetch NCBI datasets executable
        run: |
          CMD="curl -Ls https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets > datasets" \
          FALLBACK=s3://goat/resources/datasets \
          RESOURCES=${{ needs.set-taxroot.outputs.resources }} \
          ./scripts/update-resources/fetch-or-fallback.sh

  update-ncbi-datasets-zip:
    needs:
      - set-taxroot
      - fetch-ncbi-datasets
    strategy:
      matrix:
        taxroot: ${{ fromJSON(needs.set-taxroot.outputs.taxroot) }}
    uses: ./.github/workflows/_update_ncbi_datasets.yml
    with:
      taxroot: ${{ matrix.taxroot }}
      resources: ${{ needs.set-taxroot.outputs.resources }}
