name: test-goat

on: push

jobs:
#   check-health-get-dockers:
#     runs-on:  self-hosted
#     steps:
#     - name: Check health
#       run:  curl -s "http://es1:9200/_cat/health"
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Get dockers
#       run:  docker pull genomehubs/genomehubs:latest

  get-ena-taxonomy-extra:
#    needs:    check-health-get-dockers
    runs-on:  self-hosted
    steps:
    - name: Get extra ENA taxonomy nodes
      run:  |
        mkdir -p sources/ena-taxonomy
        cd sources/ena-taxonomy
        bash ../../scripts/get_ena_taxonomy_extra.bash
        rm ena-taxonomy.xml.taxids resulttaxon.tax_tree2759.tsv \
          ena-taxonomy.extra.prev.jsonl ena-taxonomy.extra.prev.taxids \
          resulttaxon.tax_tree2759.extra.curr.tsv ena-taxonomy.extra.curr.jsonl
        cd   ../../

  genomehubs-init:
    needs:
#      - check-health-get-dockers
      - get-ena-taxonomy-extra
    runs-on:  self-hosted
    steps:
      - name: Clean taxdump folder and delete indices
        run: |
          mkdir -p resources/taxdump
          rm -rf resources/taxdump/*
          curl -X DELETE "es1:9200/*"
      - name: Run docker genomehubs init
        run: |
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            -v `pwd`/resources:/genomehubs/resources \
              genomehubs/genomehubs:latest bash -c \
              "genomehubs init \
                --es-host http://es1:9200 \
                --taxonomy-source ncbi \
                --config-file sources/goat.yaml \
                --taxonomy-jsonl sources/ena-taxonomy/ena-taxonomy.extra.jsonl.gz \
                --taxonomy-ncbi-root 2759 \
                --taxon-preload"

  get-ncbi-datasets:
#    needs:    check-health-get-dockers
    runs-on:  self-hosted
    steps:
      - name: Download NCBI datasets executable
        run: |
          curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > /tmp/datasets
          chmod a+x /tmp/datasets
      - name: Download NCBI eukaryota datasets zip
        run: |
          mkdir -p sources/assembly-data
          /tmp/datasets download genome taxon "Eukaryota" --dehydrated --filename sources/assembly-data/eukaryota.zip
          unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
      - name: Run docker genomehubs parse --ncbi-datasets
        run: |
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            genomehubs/genomehubs:latest bash -c \
            "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz"
      - name: Clean up expanded zip
        run: |
            rm -rf sources/assembly-data/ncbi_dataset

  get-refseq-organelles:
#    needs:    check-health-get-dockers
    runs-on:  self-hosted
    steps:
      - name: Run docker genomehubs parse --refseq-organelles
        run: |
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            genomehubs/genomehubs:latest bash -c \
            "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"
