name: test-goat

on: push

jobs:
  get-ncbi-taxdump-ena-taxonomy-extra:
    runs-on: self-hosted
    steps:
      - name: Check health
        run: |
          curl -s "http://es1:9200/_cat/health"
      - uses: actions/checkout@v2
      - run: | 
          mkdir -p resources/taxdump
          rm -rf resources/taxdump/*
          curl -X DELETE "es1:9200/*"

  get-ncbi-datasets:
    runs-on: self-hosted
    steps:
      - name: Download NCBI datasets
        run: |
          curl https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets > /tmp/datasets
          chmod a+x /tmp/datasets
          mkdir -p sources/assembly-data
          /tmp/datasets download genome taxon "Eukaryota" --dehydrated --filename sources/assembly-data/eukaryota.zip
          unzip -o -d sources/assembly-data sources/assembly-data/eukaryota.zip ncbi_dataset/data/assembly_data_report.jsonl
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            genomehubs/genomehubs:latest bash -c \
            "genomehubs parse --ncbi-datasets sources/assembly-data --outfile sources/assembly-data/ncbi_datasets_eukaryota.tsv.gz

  get-refseq-organelles:
    runs-on: self-hosted
    steps:
      - name: Download Refseq Organelles
        run: |
          docker run --rm --network=host \
            -v `pwd`/sources:/genomehubs/sources \
            genomehubs/genomehubs:latest bash -c \
            "genomehubs parse --refseq-organelles --outfile sources/assembly-data/refseq_organelles.tsv.gz"


