name: test-genomehubs

on: [push]

jobs:
  run-test-fill:
    runs-on: self-hosted
    #services:
    #  genomehubs-docker:
    #    image: genomehubs/genomehubs:latest
    #    options: -v goat-data:/usr/share/elasticsearch/data
    steps:
      - name: Check health
        run: |
          curl -s "http://es1:9200/_cat/health"
      - uses: actions/checkout@v2
      - run: mkdir -p resources
      - name: Run genomehubs init
        run: |
          pwd
          ls
          docker run --rm \
            -v `pwd`/sources:/genomehubs/sources \
            -v `pwd`/resources:/genomehubs/resources \
              genomehubs/genomehubs:latest bash -c \
              "find /genomehubs"

      - name: Run genomehubs init
        run: |
          docker run --rm \
            -v `pwd`/sources:/genomehubs/sources \
            -v `pwd`/resources:/genomehubs/resources \
              genomehubs/genomehubs:latest bash -c \
              "genomehubs init \
                --es-host es1:9200 \
                --taxonomy-path /genomehubs/resources/taxdump \
                --hub-path /genomehubs/resources \
                --taxonomy-source ncbi \
                --config-file /genomehubs/sources/goat.yaml \
                --taxonomy-ncbi-root 7088"
