name: test_api
on:
  push:
    branches:
      - feature-autoimport

jobs:
  update_api_googlesheets_data:
    runs-on:  [ self-hosted ]
    steps:
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests pyyaml

      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Get from nhm and vgl APIs
        run: |
          python3 ./scripts/api_to_tsv.py ${{ secrets.STS_AUTHORIZATION_KEY }} ${{ secrets.JGI_OFFLINE_TOKEN }}

      - name: Get Schema 2.5  status files
        run: |
          python3 ./scripts/import_status.py ${{ secrets.ORIGINAL2_5_SCHEMA }}
